# MWS Secondary Target Selection

## MWS_SPECIAL_RRLYR_SV

Maintainers:
  - Sergey Koposov (selection/catalog)
  - Andrew Cooper (secondary target code)

In [1]:
ls ../raw

rrlyrae_gaia_source_id.fits


We include all the stars from Gaia that were classified as RR Lyrae with mean G magnitudes between 14 and 19. Specifically that includes

1. All the stars from Gaia vari_rrlyrae table
2. All the stars from vari_classifier_result with RR* class

The selection criteria are:

```
WITH x as (SELECT vari_classifier_result.source_id
        FROM gaia_dr2.vari_classifier_result
        WHERE vari_classifier_result.best_class_name::text ~~ 'RR%'::text
    UNION
    SELECT vari_rrlyrae.source_id
        FROM gaia_dr2.vari_rrlyrae)
SELECT g.* FROM gaia_dr2.gaia_source as g, x
       where g.source_id = x.source_id
       and phot_g_mean_mag between 14 and 19;
```

In [2]:
pwd

'/global/projecta/projectdirs/desi/external/mws/sv/MWS_SPECIAL_RRLYR_SV/1/code'

In [3]:
import os
import numpy as np
from astropy.table import Table, Column
import astropy.io.fits as fits

In [4]:
target_class   = 'MWS_SPECIAL_RRLYR_SV'
input_filename = 'rrlyrae_gaia_source_id.fits'

REF_CAT   = 'G'
REF_EPOCH = '2015.5'

In [5]:
# Relative paths
input_path  = os.path.join('..','raw',input_filename)

# Separate bright and faint output
output_path = os.path.join('..','indata','{}.fits'.format(target_class))

output_dir  = os.path.dirname(output_path)
if not os.path.exists(output_dir):
    print('Making output directory: {}'.format(os.path.abspath(output_dir)))
    os.makedirs(dir)

In [6]:
print('Reading input: {}'.format(os.path.abspath(input_path)))
d = Table.read(input_path)
print('Read {:d} rows'.format(len(d)))

Reading input: /global/projecta/projectdirs/desi/external/mws/sv/MWS_SPECIAL_RRLYR_SV/1/raw/rrlyrae_gaia_source_id.fits
Read 137249 rows


In [9]:
print('First 3 rows:')
print(d[0:3])
print(d.colnames)

First 3 rows:
     source_id     
-------------------
6026375677963210240
5393238919477110528
 834731365039417856
['source_id']


In [8]:
# Match on Gaia source ID

In [25]:
import re
import glob

In [22]:
gaia_sources = glob.glob('/global/project/projectdirs/cosmo/staging/gaia/dr2/gaia-source/GaiaSource_*.fits')

In [97]:
pat = 'GaiaSource_(:?[0-9]+)_(:?[0-9]+).fits'
lows, highs = list(), list()
for fn in gaia_sources:
    m   = re.match(pat,os.path.basename(fn))
    low, high = m.groups()
    lows.append(int(low))
    highs.append(int(high))
lows  = np.array(lows)
highs = np.array(highs)

In [98]:
np.argmin(lows), np.argmax(lows)

(19761, 6013)

In [99]:
np.argmin(highs), np.argmax(highs)

(19761, 6013)

In [100]:
lows[0:3], highs[0:3]

(array([6003463230033802752, 4112108822858560896, 4269275660632871040]),
 array([6003509997942660480, 4112131504619931520, 4269297311621972864]))

In [101]:
ifile = np.arange(0,len(lows))
assert(np.all(np.argsort(lows) == np.argsort(highs)))
s     = np.argsort(lows)
ifile = ifile[s]
lows  = lows[s]
highs = highs[s]

In [102]:
lows[0:3], highs[0:3]

(array([     4295806720, 478047042392960, 933966408964096]),
 array([ 477948256339712,  933932049175296, 1387484890373248]))

In [143]:
low_edge  = np.searchsorted(lows,d['source_id'],side='left')
high_edge = np.searchsorted(highs,d['source_id'],side='right')+1

In [146]:
(high_edge-low_edge > 0).sum()

22

In [144]:
assert(np.all(high_edge - low_edge == 0))

AssertionError: 

In [112]:
print(ifile[low_edge[0:3]])

[40056 61041 37517]


In [113]:
low_edge[0],high_edge[0], ifile[low_edge[0]], ifile[high_edge[0]]

(54770, 54770, 40056, 40056)

In [114]:
print(gaia_sources[ifile[low_edge[0]]])

/global/project/projectdirs/cosmo/staging/gaia/dr2/gaia-source/GaiaSource_6026391792684395008_6026414543209870208.fits


In [107]:
d['source_id'][0] >= low_edge[0], d['source_id'][0] < high_edge[0]

(True, False)

In [90]:
d['source_id'][0]-6026391792684395008,6026414543209870208-d['source_id'][0]

(-16114721184768, 38865246659968)

In [18]:
t = Table.read('/global/project/projectdirs/cosmo/staging/gaia/dr2/gaia-source/GaiaSource_1000172165251650944_1000424567594791808.fits')

In [21]:
t[np.argsort(t['source_id'])][-3:]

<Table length=3>
    solution_id             designation          ... lum_percentile_upper
       int64                  bytes28            ...       float32       
------------------- ---------------------------- ... --------------------
1635721458409799680 Gaia DR2 1000424537530485888 ...            1.1073885
1635721458409799680 Gaia DR2 1000424537530635008 ...                  nan
1635721458409799680 Gaia DR2 1000424567594791808 ...                  nan

In [14]:
!cat /global/project/projectdirs/cosmo/staging/gaia/dr2/README

Gaia DR2 FITS files

csv-files.txt: a list of CSV files in the Gaia-DR2 release.

mkdir CSV-gaia-source
python get.py

-> reads csv-files.txt, downloads all files to CSV-gaia-source

mkdir gaia-source-orig
python conv.py

-> reads CSV files, produces FITS files

mkdir gaia-source
python conv2.py

-> reads FITS files, fixes some issues.



In [52]:
BRIGHT_TIME_BRIGHT_LIMIT = 16.0

print('Mag range: {:5.2f} < G < {:5.2f}'.format(d['phot_g_mean_mag'].min() ,d['phot_g_mean_mag'].max()))
print('Targets brighter than G = 16: {}/{} ({:3.2%})'.format((d['phot_g_mean_mag'] < BRIGHT_TIME_BRIGHT_LIMIT).sum(),
                                                   len(d),
                                                   (d['phot_g_mean_mag'] < BRIGHT_TIME_BRIGHT_LIMIT).sum()/len(d)
                                                  ))

bright_time_targets = d['phot_g_mean_mag'] > BRIGHT_TIME_BRIGHT_LIMIT

Mag range: 10.67 < G < 20.88
Targets brighter than G = 16: 75258/291411 (25.83%)


Adjust to secondary target data model:

In [53]:
output = d['ra','dec','source_id'][bright_time_targets]
output.rename_columns(['ra','dec','source_id'],['RA','DEC','REF_ID'])
output.add_column(Column(np.repeat(False,len(output)),'OVERRIDE'))
output.add_column(Column(np.zeros(len(output),dtype=np.float32),'PMRA'))
output.add_column(Column(np.zeros(len(output),dtype=np.float32),'PMDEC'))
output.add_column(Column(np.repeat(REF_CAT,len(output)),'REF_CAT'))
output.add_column(Column(np.repeat(REF_EPOCH,len(output)),'REF_EPOCH'))

Add header:

In [54]:
output.meta['VRAWDATA'] = int(os.path.abspath(input_path).split(os.path.sep)[-3])

In [55]:
output[0:3]

<Table length=3>
       RA              DEC               REF_ID       ... REF_CAT REF_EPOCH
    float64          float64             int64        ...   str1     str6  
---------------- ---------------- ------------------- ... ------- ---------
328.530788027781 2.53707028993252 2693964742599255040 ...       G    2015.5
 328.59327920521 2.44939161551723 2693916226648580224 ...       G    2015.5
328.591951469507 2.36698433447594 2693912374062424192 ...       G    2015.5

Write output:

In [56]:
print('Writing {:d} rows of output to {}'.format(len(output),os.path.abspath(output_path)))
output.write(output_path,overwrite=True)

Writing 216153 rows of output to /Users/apcooper/astro/data/desi/secondary/MWS_SPECIAL_DDOGIANTS_SV/1/indata/MWS_SPECIAL_DDOGIANTS_SV.fits
